# Generated by Django 2.1.2 on 2018-11-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab5App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskModel',
            new_name='Task',
        ),
    ]
